### ISSUE TITLE
Bot is not responding

### ISSUE THREAD

**Issue by TomlDev** [blackoders/drinkly#10]
Thanks for sharing this, but the bot seems to be offline:
![grafik](https://github.com/user-attachments/assets/b039bf42-39f1-4fae-990c-4825e39acd08)

**Comment by blackode** [comment]
@TomlDev Glad that you checked. But it is not a live one nor hosted . It's just the code. 
You need to setup your config keys. 
You can hack it however you like and host the bot in your server.

GoddLuck :)

**Comment by TomlDev** [comment]
Aight, I thought you hosted it too.

I tried to get it to running and it was a mess to get the old erlang version to run.
But it didn't work with the Dockerfile and with a local installation.

Docker:
```
$ sudo docker build -t drinkly-bot .
[+] Building 26.8s (6/16)                                                                                                                                                                docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                               0.1s
 => => transferring dockerfile: 1.07kB                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/node:10.16.1                                                                                                                                    1.7s
 => [internal] load .dockerignore                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                    0.0s
 => [stage-2  1/12] FROM docker.io/library/node:10.16.1@sha256:d569181ad77f171cc654c75c954d841160b910fe64da7a8b399cda6104b19858                                                                   24.2s
 => => resolve docker.io/library/node:10.16.1@sha256:d569181ad77f171cc654c75c954d841160b910fe64da7a8b399cda6104b19858                                                                              0.0s
 => => sha256:d569181ad77f171cc654c75c954d841160b910fe64da7a8b399cda6104b19858 1.21kB / 1.21kB                                                                                                     0.0s
 => => sha256:808fa565603813781b6683fb402261a0a7396db06350165de6f79c8c809abc11 7.76kB / 7.76kB                                                                                                     0.0s
 => => sha256:a4d8138d0f6b5a441aaa533faf5fe0c3996a6ca42643c46f4402c7e8bda53742 45.34MB / 45.34MB                                                                                                   1.6s
 => => sha256:dbdc36973392a980d56b8fab63383ae44582f6502001d8bbdd543aa3bf1d746e 10.79MB / 10.79MB                                                                                                   0.8s
 => => sha256:fdcdf519622ff8d3cb8000a77e69fc44e7d5ebe8c39f8d89885ffba337b193f8 2.21kB / 2.21kB                                                                                                     0.0s
 => => sha256:f59d6d019dd5b8398eb8d794e3fafe31f9411cc99a71dabfa587bf732b4a7385 4.34MB / 4.34MB                                                                                                     0.6s
 => => sha256:aaef3e0262580b9032fc6741fb099c7313834c7cf332500901e87ceeb38ac153 50.07MB / 50.07MB                                                                                                   2.8s
 => => sha256:6e454d3b6c28c7fb982f4ecb3a0ecf6ab6b3fc31179b70fe38718c9b58fa65ee 215.10MB / 215.10MB                                                                                                 5.7s
 => => extracting sha256:a4d8138d0f6b5a441aaa533faf5fe0c3996a6ca42643c46f4402c7e8bda53742                                                                                                          4.4s
 => => sha256:c717a7c205aa7a6401661daa98aad164bed40a50b51994b70b55adbff346b33b 4.17kB / 4.17kB                                                                                                     2.2s
 => => sha256:fe0a90ef0ea3a92b29ce91b5b8c8edc88faf8727e3133414180ac1fc7823ef1d 20.65MB / 20.65MB                                                                                                   3.3s
 => => sha256:e6885e7e909bdb36a2789c24acc744fc18f40f08ea367a52fdbe951e5f2f49c8 1.40MB / 1.40MB                                                                                                     3.6s
 => => sha256:0504a9888aa4e351d823f2e1222039d6cd9098bf2ddb8a8c18d1bcbb72717ea1 295B / 295B                                                                                                         3.6s
 => => extracting sha256:dbdc36973392a980d56b8fab63383ae44582f6502001d8bbdd543aa3bf1d746e                                                                                                          0.5s
 => => extracting sha256:f59d6d019dd5b8398eb8d794e3fafe31f9411cc99a71dabfa587bf732b4a7385                                                                                                          0.1s
 => => extracting sha256:aaef3e0262580b9032fc6741fb099c7313834c7cf332500901e87ceeb38ac153                                                                                                          3.6s
 => => extracting sha256:6e454d3b6c28c7fb982f4ecb3a0ecf6ab6b3fc31179b70fe38718c9b58fa65ee                                                                                                         11.1s
 => => extracting sha256:c717a7c205aa7a6401661daa98aad164bed40a50b51994b70b55adbff346b33b                                                                                                          0.0s
 => => extracting sha256:fe0a90ef0ea3a92b29ce91b5b8c8edc88faf8727e3133414180ac1fc7823ef1d                                                                                                          1.8s
 => => extracting sha256:e6885e7e909bdb36a2789c24acc744fc18f40f08ea367a52fdbe951e5f2f49c8                                                                                                          0.1s
 => => extracting sha256:0504a9888aa4e351d823f2e1222039d6cd9098bf2ddb8a8c18d1bcbb72717ea1                                                                                                          0.0s
 => [internal] load build context                                                                                                                                                                  3.6s
 => => transferring context: 44.19MB                                                                                                                                                               3.5s
 => ERROR [stage-2  2/12] RUN ./pacman -Syyu --noconfirm                                                                                                                                           0.7s
------                                                                                                                                                                                                  
 > [stage-2  2/12] RUN ./pacman -Syyu --noconfirm:
0.233 /bin/sh: 1: ./pacman: not found
------

 3 warnings found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 30)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 31)
 - JSONArgsRecommended: JSON arguments recommended for CMD to prevent unintended behavior related to OS signals (line 59)
Dockerfile:16
--------------------
  14 |     
  15 |     # packman setup
  16 | >>> RUN ./pacman -Syyu --noconfirm
  17 |     RUN ./pacman-db-upgrade
  18 |     RUN ./pacman -S --noconfirm nodejs wkhtmltopdf
--------------------
ERROR: failed to solve: process "/bin/sh -c ./pacman -Syyu --noconfirm" did not complete successfully: exit code: 127
```

But now when I run it with
```
mix deps.get
mix compile
mix run --no-halt
```

I get this error:
```
$ mix run --no-halt

07:42:49.669 [info]  [swarm on nonode@nohost] [tracker:init] started

07:42:49.693 [info]  Accepting connections on port 8080

07:42:49.712 [debug] [:nonode@nohost][Elixir.Quantum.JobBroadcaster] Loading Initial Jobs from Config

07:42:49.716 [debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Unknown last execution time, using now

07:42:49.782 [error] GenServer #PID<0.322.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:49.782 [error] GenServer #PID<0.320.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:49.782 [error] GenServer #PID<0.321.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:49.783 [error] GenServer #PID<0.323.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:49.783 [error] GenServer #PID<0.332.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:49.784 [error] GenServer #PID<0.333.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:49.784 [error] GenServer #PID<0.334.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.087 [info]  GET https://api.telegram.org/bot/getMe -> 404 (224.087 ms)

07:42:50.096 [debug] 
>>> REQUEST >>>
(no query)
Content-Type: application/json

(no body)

<<< RESPONSE <<<
server: nginx/1.18.0
date: Fri, 08 Nov 2024 07:42:50 GMT
content-type: application/json
content-length: 55
connection: keep-alive
strict-transport-security: max-age=31536000; includeSubDomains; preload
access-control-allow-origin: *
access-control-expose-headers: Content-Length,Content-Type,Date,Server,Connection

%{description: "Not Found", error_code: 404, ok: false}

07:42:50.126 [info]  POST https://api.telegram.org/bot/deleteWebhook -> 404 (22.181 ms)

07:42:50.126 [debug] 
>>> REQUEST >>>
(no query)
Content-Type: application/json

%{}

<<< RESPONSE <<<
server: nginx/1.18.0
date: Fri, 08 Nov 2024 07:42:50 GMT
content-type: application/json
content-length: 55
connection: keep-alive
strict-transport-security: max-age=31536000; includeSubDomains; preload
access-control-allow-origin: *
access-control-expose-headers: Content-Length,Content-Type,Date,Server,Connection

%{description: "Not Found", error_code: 404, ok: false}

07:42:50.126 [info]  Started Drinkly Bot

07:42:50.127 [error] GenServer #PID<0.347.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.127 [error] GenServer #PID<0.348.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.127 [error] GenServer #PID<0.349.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.128 [error] GenServer #PID<0.350.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.128 [error] GenServer #PID<0.351.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.129 [error] GenServer #PID<0.352.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.129 [error] GenServer #PID<0.353.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.130 [error] GenServer #PID<0.357.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.131 [error] GenServer #PID<0.358.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.131 [error] GenServer #PID<0.359.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.131 [error] GenServer #PID<0.360.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.131 [error] GenServer #PID<0.361.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.131 [error] GenServer #PID<0.362.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.133 [error] GenServer #PID<0.363.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.134 [error] GenServer #PID<0.367.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.134 [error] GenServer #PID<0.368.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.134 [error] GenServer #PID<0.369.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.134 [error] GenServer #PID<0.370.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.134 [error] GenServer #PID<0.371.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.135 [error] GenServer #PID<0.372.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.135 [error] GenServer #PID<0.373.0> terminating
** (RuntimeError) connect raised ArgumentError exception. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details
    (postgrex) lib/postgrex/protocol.ex:129: Postgrex.Protocol.host_and_port/1
    (postgrex) lib/postgrex/protocol.ex:65: Postgrex.Protocol.connect/1
    (db_connection) lib/db_connection/connection.ex:69: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

07:42:50.141 [info]  Application drinkly exited: shutdown

07:42:52.634 [debug] Tzdata polling for update.

07:42:53.019 [info]  tzdata release in place is from a file last modified Wed, 11 Sep 2019 19:35:17 GMT. Release file on server was last modified Thu, 05 Sep 2024 18:47:42 GMT.

07:42:53.022 [debug] Tzdata downloading new data from https://data.iana.org/time-zones/tzdata-latest.tar.gz

07:42:53.494 [debug] Tzdata data downloaded. Release version 2024b.

07:42:53.683 [error] GenServer :tzdata_release_updater terminating
** (ArgumentError) argument error
    :erlang.element(1, :error)
    (tzdata) lib/tzdata/util.ex:223: Tzdata.Util.to_int/1
    (tzdata) lib/tzdata/parser.ex:38: Tzdata.Parser.process_rule/1
    (tzdata) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
    (tzdata) lib/tzdata/parser.ex:86: Tzdata.Parser.process_zone/5
    (tzdata) lib/tzdata/parser.ex:24: Tzdata.Parser.process_tz_list/1
Last message: :check_if_time_to_update
State: []

07:42:54.673 [info]  [swarm on nonode@nohost] [tracker:cluster_wait] joining cluster..

07:42:54.673 [info]  [swarm on nonode@nohost] [tracker:cluster_wait] no connected nodes, proceeding without sync
```
